name: CI PIPELINE

on:
  push:
    branches:
      - main
      - test-pipeline

env:
  REGISTRY: docker.io

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          key: m2-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          path: ~/.m2

      - name: Build with Maven
        run: |
          find . -name "pom.xml" -exec dir={} \; -exec mvn -f {} -B clean install \;

    outputs:
      commit-sha: ${{ github.sha }}

  docker-build:
    needs: build-and-test
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        service: [ eureka-server, api-gateway, auth-service, company-service ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check changed files
        id: changed_files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            ${{ matrix.service }}/**

      - name: Skip if not changed
        if: steps.changed_files.outputs.any_changed != 'true'
        run: |
          echo "No changes detected in '${{ matrix.service }}'. Skipping build and push."
          exit 0

      - name: Login to DockerHub
        if: steps.changed_files.outputs.any_changed == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: set IMAGE_NAME
        if: steps.changed_files.outputs.any_changed == 'true'
        run: echo "IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}" >> $GITHUB_ENV

      - name: Build Docker image
        if: steps.changed_files.outputs.any_changed == 'true'
        run: |
          docker build \
          -t $IMAGE_NAME:latest \
          -t $IMAGE_NAME:${{ needs.build-and-test.outputs.commit-sha }} \
          ./${{ matrix.service }}
          
      - name: Push Docker images
        if: steps.changed_files.outputs.any_changed == 'true'
        run: | 
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ needs.build-and-test.outputs.commit-sha }}
            
          
